# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holtlaury',
            old_name='die',
            new_name='die1',
        ),
        migrations.RenameField(
            model_name='holtlaury',
            old_name='option',
            new_name='option1',
        ),
        migrations.AddField(
            model_name='holtlaury',
            name='die10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='holtlaury',
            name='die2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='holtlaury',
            name='die3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='holtlaury',
            name='die4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='holtlaury',
            name='die5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='holtlaury',
            name='die6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='holtlaury',
            name='die7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='holtlaury',
            name='die8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='holtlaury',
            name='die9',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='holtlaury',
            name='option10',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='holtlaury',
            name='option2',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='holtlaury',
            name='option3',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='holtlaury',
            name='option4',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='holtlaury',
            name='option5',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='holtlaury',
            name='option6',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='holtlaury',
            name='option7',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='holtlaury',
            name='option8',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='holtlaury',
            name='option9',
            field=models.BooleanField(default=0),
        ),
    ]
