# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20160116_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='holtlaury',
            name='finished',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='holtlaury',
            name='started',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='holtlaury',
            name='willingness',
            field=models.IntegerField(default=16),
        ),
    ]
