# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20160118_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='holtlaury',
            name='willingnessRand',
            field=models.IntegerField(default=16),
        ),
    ]
