# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_holtlaury_willingnessrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='holtlaury',
            name='originalPoints',
            field=models.IntegerField(default=0),
        ),
    ]
