# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20160119_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holtlaury',
            name='willingnessRand',
            field=models.IntegerField(default=15),
        ),
    ]
