# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20160119_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holtlaury',
            name='willingness',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='holtlaury',
            name='willingnessRand',
            field=models.FloatField(default=16),
        ),
    ]
