# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_investment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='investmentpoints',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='returnpoints',
        ),
        migrations.AddField(
            model_name='investment',
            name='otherinvested',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='investment',
            name='otheruser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otherreturned_set', to='games.User'),
        ),
        migrations.AddField(
            model_name='investment',
            name='points',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='investment',
            name='otherreturned',
            field=models.IntegerField(default=-1),
        ),
    ]
