# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_auto_20160214_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='returned0',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='investment',
            name='invested',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='investment',
            name='returned1',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='investment',
            name='returned10',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='investment',
            name='returned2',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='investment',
            name='returned3',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='investment',
            name='returned4',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='investment',
            name='returned5',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='investment',
            name='returned6',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='investment',
            name='returned7',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='investment',
            name='returned8',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='investment',
            name='returned9',
            field=models.IntegerField(default=-1),
        ),
    ]
