# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_auto_20160214_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='finished',
            new_name='finishedinvested',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='started',
            new_name='finishedreturned0',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='returned10',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='returned6',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='returned7',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='returned8',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='returned9',
        ),
        migrations.AddField(
            model_name='investment',
            name='finishedreturned1',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='investment',
            name='finishedreturned2',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='investment',
            name='finishedreturned3',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='investment',
            name='finishedreturned4',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='investment',
            name='finishedreturned5',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='investment',
            name='startedinvested',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='investment',
            name='startedreturned0',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='investment',
            name='startedreturned1',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='investment',
            name='startedreturned2',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='investment',
            name='startedreturned3',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='investment',
            name='startedreturned4',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='investment',
            name='startedreturned5',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
