# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_auto_20160215_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thankyou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainingComment', models.TextField(blank=True, null=True)),
                ('gamesComment', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.User')),
            ],
        ),
    ]
