# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_thankyou'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pretest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.IntegerField(default=-1)),
                ('question2', models.IntegerField(default=-1)),
                ('question3', models.IntegerField(default=-1)),
                ('question4', models.IntegerField(default=-1)),
                ('question5', models.IntegerField(default=-1)),
                ('question6', models.IntegerField(default=-1)),
                ('question7', models.IntegerField(default=-1)),
                ('correct1', models.IntegerField(default=-1)),
                ('correct2', models.IntegerField(default=-1)),
                ('correct3', models.IntegerField(default=-1)),
                ('correct4', models.IntegerField(default=-1)),
                ('correct5', models.IntegerField(default=-1)),
                ('correct6', models.IntegerField(default=-1)),
                ('correct7', models.IntegerField(default=-1)),
                ('questionclicked1', models.IntegerField(default=-1)),
                ('questionclicked2', models.IntegerField(default=-1)),
                ('questionclicked3', models.IntegerField(default=-1)),
                ('questionclicked4', models.IntegerField(default=-1)),
                ('questionclicked5', models.IntegerField(default=-1)),
                ('questionclicked6', models.IntegerField(default=-1)),
                ('questionclicked7', models.IntegerField(default=-1)),
                ('questionrightclicked1', models.IntegerField(default=-1)),
                ('questionrightclicked2', models.IntegerField(default=-1)),
                ('questionrightclicked3', models.IntegerField(default=-1)),
                ('questionrightclicked4', models.IntegerField(default=-1)),
                ('questionrightclicked5', models.IntegerField(default=-1)),
                ('questionrightclicked6', models.IntegerField(default=-1)),
                ('questionrightclicked7', models.IntegerField(default=-1)),
                ('questionhovered1', models.IntegerField(default=-1)),
                ('questionhovered2', models.IntegerField(default=-1)),
                ('questionhovered3', models.IntegerField(default=-1)),
                ('questionhovered4', models.IntegerField(default=-1)),
                ('questionhovered5', models.IntegerField(default=-1)),
                ('questionhovered6', models.IntegerField(default=-1)),
                ('questionhovered7', models.IntegerField(default=-1)),
                ('questionhoveredseconds1', models.FloatField(default=-1)),
                ('questionhoveredseconds2', models.FloatField(default=-1)),
                ('questionhoveredseconds3', models.FloatField(default=-1)),
                ('questionhoveredseconds4', models.FloatField(default=-1)),
                ('questionhoveredseconds5', models.FloatField(default=-1)),
                ('questionhoveredseconds6', models.FloatField(default=-1)),
                ('questionhoveredseconds7', models.FloatField(default=-1)),
                ('startedquestion1', models.DateTimeField(default=django.utils.timezone.now)),
                ('finishedquestion1', models.DateTimeField(default=django.utils.timezone.now)),
                ('startedquestion2', models.DateTimeField(default=django.utils.timezone.now)),
                ('finishedquestion2', models.DateTimeField(default=django.utils.timezone.now)),
                ('startedquestion3', models.DateTimeField(default=django.utils.timezone.now)),
                ('finishedquestion3', models.DateTimeField(default=django.utils.timezone.now)),
                ('startedquestion4', models.DateTimeField(default=django.utils.timezone.now)),
                ('finishedquestion4', models.DateTimeField(default=django.utils.timezone.now)),
                ('startedquestion5', models.DateTimeField(default=django.utils.timezone.now)),
                ('finishedquestion5', models.DateTimeField(default=django.utils.timezone.now)),
                ('startedquestion6', models.DateTimeField(default=django.utils.timezone.now)),
                ('finishedquestion6', models.DateTimeField(default=django.utils.timezone.now)),
                ('startedquestion7', models.DateTimeField(default=django.utils.timezone.now)),
                ('finishedquestion7', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.User')),
            ],
        ),
        migrations.AddField(
            model_name='thankyou',
            name='pretestComment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
