# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_auto_20160216_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstgame',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AddField(
            model_name='user',
            name='secondgame',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AddField(
            model_name='user',
            name='thirdgame',
            field=models.CharField(default='', max_length=13),
        ),
    ]
