# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_auto_20160218_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experimentearning',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='totalearning',
            field=models.FloatField(default=0),
        ),
    ]
