# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-28 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_auto_20160219_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='finishedstudy',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='startedstudy',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
