# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0022_auto_20160227_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='optout',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='postpone',
            field=models.BooleanField(default=0),
        ),
    ]
