# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0023_auto_20160303_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='version',
            field=models.CharField(default='', max_length=13),
        ),
    ]
